# Generated by Django 6.1 on 2026-08-26 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('cancelada', 'Cancelada'), ('pagada', 'Pagada')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoteInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=20, unique=True)),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comanda')),
                ('lote_descontado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.loteinsumo')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plato')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loteinsumo')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plato')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario'),
        ),
    ]
