# Generated by Django 6.1 on 2026-08-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comanda',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Comanda', 'verbose_name_plural': 'Comandas'},
        ),
        migrations.AlterModelOptions(
            name='detallecomanda',
            options={'verbose_name': 'Detalle de comanda', 'verbose_name_plural': 'Detalles de comanda'},
        ),
        migrations.AlterModelOptions(
            name='loteinsumo',
            options={'ordering': ['fecha_ingreso'], 'verbose_name': 'Lote de insumo', 'verbose_name_plural': 'Lotes de insumos'},
        ),
        migrations.AlterModelOptions(
            name='plato',
            options={'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
        migrations.AlterModelOptions(
            name='recetaplato',
            options={'verbose_name': 'Receta de plato', 'verbose_name_plural': 'Recetas de platos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='detallecomanda',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loteinsumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='detallecomanda',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.comanda'),
        ),
        migrations.AlterField(
            model_name='detallecomanda',
            name='lote_descontado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_descontados', to='core.loteinsumo'),
        ),
        migrations.AlterField(
            model_name='loteinsumo',
            name='categoria',
            field=models.CharField(choices=[('carnes', 'Carnes'), ('pulpas_fruta', 'Pulpas de Fruta'), ('verduras', 'Verduras'), ('harinas', 'Harinas'), ('lacteos', 'Lácteos'), ('bebidas', 'Bebidas'), ('otros', 'Otros Insumos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recetaplato',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en_recetas', to='core.loteinsumo'),
        ),
        migrations.AlterField(
            model_name='recetaplato',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='core.plato'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado/Mesero')], default='empleado', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='recetaplato',
            unique_together={('plato', 'insumo')},
        ),
        migrations.CreateModel(
            name='AjusteMerma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(choices=[('desperdicio', 'Desperdicio'), ('danio', 'Daño'), ('caducidad', 'Caducidad'), ('error_conteo', 'Error de conteo')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_merma', to='core.loteinsumo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_merma', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Ajuste de merma',
                'verbose_name_plural': 'Ajustes de merma',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_sesion', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Registro de sesión',
                'verbose_name_plural': 'Registros de sesión',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
