# Generated by Django 6.1 on 2026-08-31 21:58

import django.db.models.deletion
from decimal import Decimal, InvalidOperation
from django.db import connection, migrations, models


def repair_decimal_columns(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('SELECT id, total FROM core_comanda')
        for comanda_id, total in cursor.fetchall():
            try:
                value = Decimal(str(total))
                if not value.is_finite():
                    raise InvalidOperation
            except (InvalidOperation, TypeError, ValueError):
                value = Decimal('0')
            if total != value:
                cursor.execute(f'UPDATE core_comanda SET total = {value} WHERE id = {int(comanda_id)}')

        cursor.execute('SELECT id, precio_unitario FROM core_detallecomanda')
        for detalle_id, precio in cursor.fetchall():
            try:
                value = Decimal(str(precio))
                if not value.is_finite():
                    raise InvalidOperation
            except (InvalidOperation, TypeError, ValueError):
                value = Decimal('0')
            if precio != value:
                cursor.execute(f'UPDATE core_detallecomanda SET precio_unitario = {value} WHERE id = {int(detalle_id)}')

        cursor.execute('SELECT id FROM core_comanda ORDER BY id')
        for comanda_id, in cursor.fetchall():
            cursor.execute(f'UPDATE core_comanda SET mesa = {int(comanda_id)} WHERE id = {int(comanda_id)}')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_factura_detallefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='mesa',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(repair_decimal_columns, migrations.RunPython.noop),
        migrations.AddField(
            model_name='plato',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallecomanda',
            name='lote_descontado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_descontados', to='core.loteinsumo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado/Mesero'), ('cajero', 'Cajero')], default='empleado', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'enviada'])), fields=('mesa',), name='unique_active_comanda_per_mesa'),
        ),
    ]
