# Generated by Django 6.1 on 2026-09-01 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comanda_mesa_alter_comanda_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('detalle_comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='core.detallecomanda')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='core.loteinsumo')),
            ],
            options={
                'ordering': ['fecha_hora', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=120)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
